# Generated by Django 5.2.1 on 2025-05-18 10:25

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPoints',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(blank=True, choices=[('Central Province', 'Central Province'), ('Eastern Province', 'Eastern Province'), ('North Central Province', 'North Central Province'), ('Northern Province', 'Northern Province'), ('North Western Province', 'North Western Province'), ('Sabaragamuwa Province', 'Sabaragamuwa Province'), ('Southern Province', 'Southern Province'), ('Uva Province', 'Uva Province'), ('Western Province', 'Western Province')], max_length=250)),
                ('city', models.CharField(blank=True, choices=[('Ampara District', 'Ampara District'), ('Anuradhapura District', 'Anuradhapura District'), ('Badulla District', 'Badulla District'), ('Batticaloa District', 'Batticaloa District'), ('Colombo District', 'Colombo District'), ('Galle District', 'Galle District'), ('Gampaha District', 'Gampaha District'), ('Hambantota District', 'Hambantota District'), ('Jaffna District', 'Jaffna District'), ('Kalutara District', 'Kalutara District'), ('Kandy District', 'Kandy District'), ('Kegalle District', 'Kegalle District'), ('Kilinochchi District', 'Kilinochchi District'), ('Kurunegala District', 'Kurunegala District'), ('Mannar District', 'Mannar District'), ('Matale District', 'Matale District'), ('Matara District', 'Matara District'), ('Monaragala District', 'Monaragala District'), ('Mullaitivu District', 'Mullaitivu District'), ('Nuwara Eliya District', 'Nuwara Eliya District'), ('Polonnaruwa District', 'Polonnaruwa District'), ('Puttalam District', 'Puttalam District'), ('Ratnapura District', 'Ratnapura District'), ('Trincomalee District', 'Trincomalee District'), ('Vavuniya District', 'Vavuniya District')], max_length=250)),
                ('latitude', models.FloatField(default=1)),
                ('longitude', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'BoardingPoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=255)),
                ('route_number', models.CharField(max_length=255)),
                ('number_of_sections', models.IntegerField()),
                ('sections', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'Routes',
                'managed': False,
            },
        ),
    ]
