# Generated by Django 5.2.1 on 2025-05-19 10:08

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=24)),
                ('route_name', models.CharField(max_length=255)),
                ('bus_id', models.CharField(max_length=24)),
                ('bus_number', models.CharField(max_length=255)),
                ('bus_name', models.CharField(max_length=255)),
                ('trip_start_time', models.DateTimeField()),
                ('revenue', models.IntegerField(default=0)),
                ('company_3_percent_cut', models.IntegerField(default=0)),
                ('is_revenue_released', models.BooleanField(default=False)),
                ('is_bus_trip_cancelled', models.BooleanField(default=False)),
                ('cancellation_fee_resolved', models.BooleanField(default=False)),
                ('seats', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'BusTrips',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='boardingpoints',
            table='BoardingPoints',
        ),
    ]
